name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: "3.24.5" # Update to your Flutter version

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release
        if: runner.os == 'Linux'

      - name: Build Android App Bundle
        run: flutter build appbundle --release
        if: runner.os == 'Linux'

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: android-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: build
    if: github.event_name == 'push' # Typically only build iOS for releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ipa --release

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-artifact
          path: build/ios/ipa/*.ipa
